### ISSUE TITLE
Run on windows [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by heinrichI** [sankovalev/Look4Face#9]
I am trying to run Look4Face on windows. After selecting a photo by pressing the search button, the following error appears:
![image](https://user-images.githubusercontent.com/7752557/119455151-fe2fc700-bd41-11eb-8f4f-dd19e1544f2e.png)

**Comment by sankovalev** [comment]
From [briefly](https://github.com/sankovalev/Look4Face#briefly): "For Linux and Mac OS"

Unfortunately, I can't say what the reason for the error is, but I will assume that [OSError](https://docs.python.org/3/library/exceptions.html#OSError) raises because of the path format, which is different in Windows from Linux.
